apiVersion: group.googleworkspace.jet.crossplane.io/v1alpha1
kind: Members
metadata:
  name: example-group-a-members
spec:
  forProvider:
    groupId: 03vac5uf1t2pwla
    members:
      - email: joakim.hansson@zeronorth.com
        role: OWNER
  providerConfigRef:
    name: default