---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-googleworkspace-config
  labels:
    app: crossplane-provider-jet-googleworkspace
spec:
  image: joakimhew/provider-jet-googleworkspace-controller:v0.1.0-alpha
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-jet-googleworkspace
spec:
  package: joakimhew/provider-jet-googleworkspace:v0.1.0-alpha
  controllerConfigRef:
    name: jet-googleworkspace-config
